### ISSUE TITLE
新規登録PUTでPDO Exception

### ISSUE THREAD

**Issue by yueguchi** [yueguchi/aws-cfn-template-with-lumen#1]
```
==> /var/log/httpd/error.log <==
[Sun Nov 25 09:54:20.817190 2018] [php7:error] [pid 4989] [client 10.0.0.173:45582] PHP Fatal error:  Class 'PDO' not found in /var/www/html/aws-cfn-template-with-lumen/vendor/illuminate/database/Connection.php on line 1259

==> storage/logs/lumen-2018-11-25.log <==
[2018-11-25 09:54:20] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Class 'PDO' not found in /var/www/html/aws-cfn-template-with-lumen/vendor/illuminate/database/Connection.php:1259
Stack trace:
#0 /var/www/html/aws-cfn-template-with-lumen/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class 'PDO' not found at /var/www/html/aws-cfn-template-with-lumen/vendor/illuminate/database/Connection.php:1259)
[stacktrace]
#0 /var/www/html/aws-cfn-template-with-lumen/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\\Lumen\\Application->handleShutdown()
#1 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#2 {main}
"} 

```

**Comment by yueguchi** [comment]
httpd.confを元に戻してreloadしたら直ったが、

```
	Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sub' cannot be null (SQL: insert into `users` (`sub`, `email`, `updated_at`, `created_at`) values (, , 2018-11-25 12:27:14, 2018-11-25 12:27:14)) in /var/www/html/aws-cfn-template-with-lumen/vendor/illuminate/database/Connection.php:664
```
あとは簡単。渡っていないだけ
